version: "3"

services:
  web:
    build: .
    command: npm run debug
    volumes:
      - ./dist:/doppelgangster_gatekeeper_frontend/dist
    env_file:
      - .env
    ports:
      - "80:80"
      - "9222:9222"